
import shutil
import time
import os
from pathlib import Path
from urllib.parse import urlparse
from typing import List, Optional
import browser_cookie3
from colorama import init, Fore, Back, Style
from EnhancedMenu import Enhanced_Menu

COOKIE_DIRECTORY = r"cookies"
os.makedirs(COOKIE_DIRECTORY, exist_ok=True)

class CookieManager:
    """Manages cookies for authentication"""
    def __init__(self):
        self.cookie_directory = Path(COOKIE_DIRECTORY)
        self.cookie_directory.mkdir(exist_ok=True)
        self.current_cookie_file = None
        self.cookie_sources = {
            'chrome': browser_cookie3.chrome,
            'firefox': browser_cookie3.firefox,
            'edge': browser_cookie3.edge,
            'opera': browser_cookie3.opera,
            'opera_gx': browser_cookie3.opera_gx,
            'brave': browser_cookie3.brave,
            'safari': browser_cookie3.safari
        }

    def get_status(self):
        """Get cookie status"""
        Enhanced_Menu.print_header("Checking available browser cookies....")
        available_browsers = []
        failed_browsers = []
        for browser, cookie_func in self.cookie_sources.items():
            try:
                cookies = cookie_func(domain_name="music.youtube.com")
                if cookies and len(list(cookies)) > 0:
                    available_browsers.append(browser)
                    Enhanced_Menu.print_color("Cookies found")
                else:
                    Enhanced_Menu.print_status("No cookies found", "failure")
            except Exception as e:
                failed_browsers.append(browser)
                Enhanced_Menu.print_status(f"{browser}: Error - {e}", "failure")
        if available_browsers:
            Enhanced_Menu.print_status(f"Available cookies from {', '.join(available_browsers)}", "success")
            return True
        else:
            Enhanced_Menu.print_status("No browser cookies found for Youtube Music", "error")
            return False

    def extract_cookies(self, browser_name: str = 'brave') -> Optional[Path]:
        """Extract cookies from your browser of choice & saves to files"""
        if browser_name not in self.cookie_sources:
            Enhanced_Menu.print_status("Browser not supported", "error")
            Enhanced_Menu.print_status(f"Available browsers are: {', '.join(self.cookie_sources.keys())}", "info")
            return None
        Enhanced_Menu.print_header(f"Extracting cookies from {browser_name}....")
        try:
            domains = ['music.youtube.com', 'youtube.com']
            all_cookies = []
            for domain in domains:
                try:
                    cookies = self.cookie_sources[browser_name](domain_name=domain)
                    for cookie in cookies:
                        if cookie not in all_cookies:
                            all_cookies.append(cookie)
                    Enhanced_Menu.print_status(f"Found {len(list(cookies))} cookies for {domain}", "success")
                except Exception as e:
                    Enhanced_Menu.print_status(f"Couldn't get cookies for {domain}: {e}", "error")
            if not all_cookies:
                Enhanced_Menu.print_status(f"No cookies found for Youtube Music in {browser_name}", "info")
                return None
            cookie_file = self.cookie_directory / f"{browser_name}_cookies.txt"
            with open(cookie_file, "w", encoding='utf-8') as f:
                f.write("# Netscape HTTP cookie file\n")
                f.write("# This file was generated by Youtube Downloader\n")
                f.write("# https://curl.haxx.se/docs/http-cookies.html\n\n")
                for cookie in all_cookies:
                    netloc = urlparse(cookie.domain).netloc if cookie.domain.startswith('http') else cookie.domain
                    if not netloc:
                        netloc = cookie.domain
                    secure = "TRUE" if cookie.secure else "FALSE"
                    f.write(f"{netloc}\t")
                    f.write("TRUE\t")
                    f.write(f"{cookie.path}\t")
                    f.write(f"{secure}\t")
                    f.write(f"{int(time.time()) + 3600*24*365}\t")
                    f.write(f"{cookie.name}\t")
                    f.write(f"{cookie.value}\n")
            Enhanced_Menu.print_status(f"Successfully extracted {len(all_cookies)} cookies to {cookie_file}", "success")
            Enhanced_Menu.print_status(f"Cookies saved to: {cookie_file}", "info")
            self.current_cookie_file = cookie_file
            return cookie_file
        except Exception as e:
            Enhanced_Menu.print_status(f"Failed to extract cookies from {browser_name}: {e}", "error")
            Enhanced_Menu.print_color("Direct cookie extraction failed for {}".format(browser_name))
            Enhanced_Menu.print_color("Try manual cookie export:")
            Enhanced_Menu.print_color("1. Install 'Get cookies.txt' extension for Chrome/Edge")
            Enhanced_Menu.print_color("2. Export cookies from music.youtube.com")
            Enhanced_Menu.print_color("3. Load the exported file using option 4")
            return None

    def load_cookies(self, cookie_file: str) -> Optional[Path]:
        """Load cookies from an existing file"""
        cookie_path = Path(cookie_file)
        if not cookie_path.exists():
            cookie_path = self.cookie_directory / cookie_file
            if not cookie_path.exists():
                cookie_path = Path(cookie_file)
                if not cookie_path.exists():
                    Enhanced_Menu.print_status(f"Cookie file not found: {cookie_file}", "failure")
                    return None
        try:
            with open(cookie_path, 'r', encoding='utf-8') as f:
                content = f.read(200)
                if "# Netscape HTTP Cookie File" not in content:
                    Enhanced_Menu.print_status(f"Warning: Cookie file may not be in Netscape format", "error")
            self.current_cookie_file = cookie_path
            Enhanced_Menu.print_status(f"Cookies loaded from: {cookie_path}", "info")
            return cookie_path
        except Exception as e:
            Enhanced_Menu.print_status(f"Failed to load cookies: {e}", "failure")
            return None

    def save_cookies(self, name: str = "cookies") -> Optional[Path]:
        """Save current cookie file to persistent storage"""
        
        # Checks for cookies to save
        if not self.current_cookie_file or not self.current_cookie_file.exists():
            Enhanced_Menu.print_status("No active cookie file to save", "error")
            return None
        try:
            timestamp = time.strftime("%Y%m%d_%H%M%S")
            save_path = self.cookie_directory / f"{name}_{timestamp}.txt"
            shutil.copy2(self.current_cookie_file, save_path)
            Enhanced_Menu.print_status(f"Cookies saved to: {save_path}", "success")
            return save_path
        except Exception as e:
            Enhanced_Menu.print_status(f"Failed to save cookies: {e}", "error")
            return None

    def list_cookies(self) -> List[Path]:
        """List all saved cookie files"""
        cookie_files = list(self.cookie_directory.glob("*.txt"))
        if not cookie_files:
            Enhanced_Menu.print_status("No saved cookies files found.", "error")
            return []
        Enhanced_Menu.print_status("Saved cookie files:", "info")
        
        # Goes through the file
        for i, cookie_file in enumerate(cookie_files, 1):
            file_size = cookie_file.stat().st_size
            mod_time = time.strftime("%Y-%m-%d %H:%M", time.localtime(cookie_file.stat().st_mtime))
            print(f"{Fore.YELLOW}[{i}]{Style.RESET_ALL} {Fore.CYAN}{cookie_file.name:30}{Style.RESET_ALL}")
            print(f"     Size: {file_size} bytes | Modified: {mod_time}")
        return cookie_files

    def clear_cookies(self):
        """Delete all cookie files from the main cookie directory if any"""
        try:
            deleted_count = 0
            cookie_files = list(self.cookie_directory.glob("*.txt"))
            if not cookie_files:
                Enhanced_Menu.print_color("No cookie files found in {}".format(self.cookie_directory))
                return
            Enhanced_Menu.print_color("Found {} cookie file(s) to delete:".format(len(cookie_files)))
            for cookie_file in cookie_files:
                Enhanced_Menu.print_color("  - {}".format(cookie_file.name))
            confirm = input("\nAre you sure you want to delete ALL {} cookie files? (y/n): ".format(len(cookie_files))).strip().lower()
            if confirm not in ['y', 'yes']:
                Enhanced_Menu.print_status("Cookie deletion cancelled.", "failure")
                return
            for cookie_file in cookie_files:
                try:
                    cookie_file.unlink()
                    deleted_count += 1
                    Enhanced_Menu.print_status(f"Deleted: {cookie_file.name}", "success")
                except Exception as e:
                    Enhanced_Menu.print_status(f"Failed to delete {cookie_file.name}: {e}", "failure")
            if self.current_cookie_file and not self.current_cookie_file.exists():
                self.current_cookie_file = None
            Enhanced_Menu.print_status(f"\nSuccessfully deleted {deleted_count} cookie file(s) from {self.cookie_directory}", "success")
        except Exception as e:
            Enhanced_Menu.print_status(f"Error clearing cookies: {e}", "error")

    # Gets cookie arguments for yt-dlp
    def get_arguments(self) -> List[str]:
        """Get yt-dlp cookie arguments if cookies are available"""
        if self.current_cookie_file and self.current_cookie_file.exists():
            return ["--cookies", str(self.current_cookie_file)]
        return []

    def interactive_menu(self):
        """Interactive cookie setup menu"""
        while True:
            Enhanced_Menu.clear_screen()
            Enhanced_Menu.print_color('=' * 50)
            Enhanced_Menu.print_header("Cookie Manager Menu")
            Enhanced_Menu.print_color('=' * 50)
            Enhanced_Menu.print_header("A simple program to help manager")
            Enhanced_Menu.print_section("Choices:- ")
            Enhanced_Menu.print_menu_item(1, "Check available browser for cookies")
            Enhanced_Menu.print_menu_item(2, "Extract cookies from browser")
            Enhanced_Menu.print_menu_item(3, "List saved cookie files")
            Enhanced_Menu.print_menu_item(4, "Load cookies from file")
            Enhanced_Menu.print_menu_item(5, "Save current cookies")
            Enhanced_Menu.print_menu_item(6, "Clear all cookie files")
            Enhanced_Menu.print_menu_item(7, "Show current cookie status")
            Enhanced_Menu.print_menu_item(8, "Return to main menu")
            Enhanced_Menu.print_section("STATUS")
            if self.current_cookie_file:
                Enhanced_Menu.print_status(f"Your active cookie files are: {self.current_cookie_file}", "success")
            else:
                Enhanced_Menu.print_status("You have no cookie files", "error")
            choice = input("Select option (1-8): ").strip()
            
            # Get cookie status
            if choice == "1":
                self.get_status()
                input("\nPress Enter to continue... ")
                
            # Get cookies from browser (Make sure to run browser in administration mode)
            elif choice == "2":
                print(f"\n====={Fore.CYAN}Available Browsers:{Style.RESET_ALL}======")
                for i, browser in enumerate(self.cookie_sources.keys(), 1):
                    Enhanced_Menu.print_color(f"{i}. {browser}")
                browser_choice = Enhanced_Menu.get_input("\nSelect browser (name or number): ", "str").strip()
                if browser_choice.isdigit():
                    browser_num = int(browser_choice)
                    if 1 <= browser_num <= len(self.cookie_sources):
                        browser_name = list(self.cookie_sources.keys())[browser_num - 1]
                        self.extract_cookies(browser_name)
                else:
                    self.extract_cookies(browser_choice)
                if self.current_cookie_file:
                    save = Enhanced_Menu.get_input("Save these cookies for future use? (y/n): ", "yn", default=True)
                    if save:
                        name = Enhanced_Menu.get_input("Enter name for cookie file (optional): ", "str").strip()
                        if not name:
                            name = "cookies"
                        self.save_cookies(name)
                
            # List cookies to choose from 
            elif choice == "3":
                cookie_files = self.list_cookies()
                if cookie_files:
                    load_choice = Enhanced_Menu.get_input("\nEnter number to load cookie file (or press Enter to skip): ", "str")
                    if load_choice.isdigit():
                        idx = int(load_choice) - 1
                        if 0 <= idx < len(cookie_files):
                            self.load_cookies(str(cookie_files[idx]))
                input("\nPress Enter to continue...")
                
            # Load cookes from chosen file path
            elif choice == "4":
                cookie_file = Enhanced_Menu.get_input("Enter cookie filename or path: ", "str").strip()
                if cookie_file:
                    self.load_cookies(cookie_file)
                input("\nPress Enter to continue... ")
                
            # Save cookies f
            elif choice == "5":
                if self.current_cookie_file:
                    name = Enhanced_Menu.get_input("Enter name for cookie file (optional): ", "str", default="cookies")
                    if not name:
                        name = "cookies"
                    self.save_cookies(name)
                else:
                    Enhanced_Menu.print_status("No active cookies to save", "info")
                input("\nPress Enter to continue...")
            
            # Delete all cookies 
            elif choice == "6":
                self.clear_cookies()
                input("\nPress Enter to continue")
            
            # Show current cookie status
            elif choice == "7":
                status = self.get_status()
                if self.current_cookie_file:
                    Enhanced_Menu.print_status(f"Active cookie file: {self.current_cookie_file.name}", "success")
                else:
                    Enhanced_Menu.print_status("No active cookie file", "info")
                input("\nPress Enter to continue...")
                
            # Stop cookie manager
            elif choice == "8":
                break
            
            else:
                Enhanced_Menu.print_status("Invalid choice", "info")
                input("\nPress Enter to continue...")
